- README.md
Added some description about internal configuration
> CY-1456 - Added some more documentation about library configuration

- package-lock.json
- package.json
- rollup.config.js
Change only for Composer compatibility.
> CY-1473 - Changed UMD version of package to be ES5 compatible

- images/README.md
- src/consts.js
- fix incorrect size
- fix jsdoc error
> images: upade README file

- styles/README.md
- styles/_colors.scss
- styles/_typography.scss
- styles/font-Quicksand-Bold.css
- styles/font-Quicksand-Light.css
- styles/font-Quicksand-Regular.css
- styles/font-Roboto-Bold.css
- styles/font-Roboto-Regular.css
* Updated colors according to latest brand guidelines
* Created typography style exposing brand font families
> CY-1826 - Improved branding styles

- jenkins/Jenkinsfile
- jenkins/build-pod.yaml
CY-3013 add new jenkins pipeline
> CY-3013 add new jenkins pipeline

- jenkins/Jenkinsfile
> Pipeline fixes

- package-lock.json
- package.json
This PR fixes audit fails during Nightly Build.
Ticket: https://cloudifysource.atlassian.net/browse/RD-2267
> RD-2267 - UI Audits fail because of severity vulnerabilities

- cypress/src/support/index.ts
Once merged I'll do a patch release.
N/A
N/A
N/A
> RD-1277 Updated `getAdminToken` command

- jenkins/Jenkinsfile
Introducing the same change as in https://github.com/cloudify-cosmo/cloudify-stage/pull/1562 .
N/A
I did not check the tests in this repository. I base on https://github.com/cloudify-cosmo/cloudify-stage/pull/1562 .
Same as in https://github.com/cloudify-cosmo/cloudify-stage/pull/1562 .
> RD-3024 Change build result to UNSTABLE when audit stage fails

- package-lock.json
- package.json
Applied:
```
npm run audit
npm audit fix
```
N/A
Only `package*.json` files updated, CI passes.
N/A
> RD-3291 Fix security issue

- package-lock.json
Bumped validator version to resolve vulnerability
N/A
N/A
N/A
> RD-3496 Bumped validator version to resolve vulnerability

- README.md
This PR adds simple description about Internal section used in UI packages release notes. In addition some sentences were rephrased to make different section more independent of each other.
N/A
N/A
N/A
> RD-4050 Add description about Internal section used in UI packages release notes

- .github/pull_request_template.md
According to [RD-4049](https://cloudifysource.atlassian.net/browse/RD-4049) I've improved our GitHub PR template. I have used new PR template in this PR description.
I have re-organized Confluence pages a bit to provide better DX (easier to find places with UI documentation).
N/A
N/A
N/A
> RD-4049 Update GitHub Pull Request template

- backend/migration.js
- backend/test/migration.test.js
- package-lock.json
- package.json
Upgraded umzug to v3
N/A
Proper unit test already exists - updated.
N/A
> RD-3353 Upgraded umzug to v3

- scripts/README.md
- scripts/load-latest-premium-docker-image.sh
- scripts/loadLatestPremiumDockerImage.sh
https://cloudifysource.atlassian.net/browse/RD-4051
N/A
N/A
N/A
> RD-4051: Providing the script for loading the latest premium docker dev image

- package-lock.json
> RD-4729 Audit failure fix

- backend/migration.ts
- backend/test/db.test.ts
- configs/eslint-common.json
- src/icons.ts
Enabled `consistent-type-imports` eslint rule as an alternative to enabling `importsNotUsedAsValues` TS compiler setting. The benefit of this solution is that, as opposed to the original solution outlined in RD-2000, this eslint rule is auto-fixable, while it fails the build in the same cases.
N/A
N/A
N/A
> RD-2000 Enable `consistent-type-imports` eslint rule

- configs/tsconfig.base.json
Enabled `forceConsistentCasingInFileNames` TS flag.
N/A
N/A
N/A
> RD-2978 Enable forceConsistentCasingInFileNames flag

- package-lock.json
- package.json
- test/types.test.ts
Upgraded TS to 4.4. Upgraded prettier and TS eslint plugin accordingly.
N/A
N/A
N/A
> RD-2537 Upgrade TS to 4.4

- .browserslistrc
- babel.config.js
- package-lock.json
- package.json
Changes consists of:
- Installing the newest version of [browserlist](https://www.npmjs.com/package/browserslist)
- Configuring browserlist with a list of [currently supported browser](https://groups.google.com/u/1/a/cloudify.co/g/cloudify-rnd-ui/c/bx5IeE7ytsw)
- Enabling [loose mode](https://babeljs.io/docs/en/babel-preset-env#loose) for babel
- Further configuration of the `browserslist` wasn't required as one of the babel package (`@babel/preset-env` was already using it under the hood)
- Sharing `browserslist` configuration across our repositories is currently hard to obtain. [There exists an option](browserslist-config-) to extends a browserslist configuration, but it's requiring from the path (to the configuration file), that it should be starting with `browserslist-config-` prefix. …
> RD-1312: Updated browserslist and babel configuration

- package-lock.json
Changes consists of relocking `package-lock.json` file via `npm audit fix` command
N/A
N/A
N/A
> RD-5340: Resolved sequalize package vulnerability

- .eslintrc.json
- configs/README.md
- configs/eslint-common-jest.json
RD-2855
- create `eslint-common-jest.json` (unfortunately, I haven't found anything else which could be shared between repos :( ) 
- modify `eslintrc.json`
**related PRs:**
- https://github.com/cloudify-cosmo/cloudify-ui-components/pull/144
- https://github.com/cloudify-cosmo/cloudify-stage/pull/2058
- https://github.com/cloudify-cosmo/cloudify-blueprint-composer/pull/1052
- https://github.com/cloudify-cosmo/cloudify-blueprint-topology/pull/209
I'll update them after releasing an updated version of cloudify-ui-common
N/A
N/A
N/A
> RD-2855: Create common ESLint configuration for Jest

- .eslintrc.json
- backend/db.ts
- backend/migration.ts
- backend/test/migration.test.ts
Changes consists of enabling `no-floating-promises` rule across the backend files and adjusting the code accordingly, to meet the rule requirements.
N/A
N/A
> RD-5453: Enabled no-floating-promises eslint rule

- scripts/get-ts-migration-progress.sh
RD-5709
- in https://github.com/cloudify-cosmo/cloudify-ui-components/pull/154 I decided to use `ts-migrate` which adds ts-expected-error instead of ts-nocheck, that's why I needed to adjust the script which calculates our TS migration
n/a
CI checks passed ✅ 
n/a
> RD-5709 modify ts-migration-progress

- package-lock.json
- packages/configs/README.md
- packages/configs/eslint-common-jest.json
- packages/configs/eslint-common-node.json
- packages/configs/eslint-common.json
- packages/configs/package.json
Replaced `scanjs` package
N/A
CI verification
Updated README
> RD-3002 Replace `scanjs` package

- packages/cypress/src/config/index.ts
- packages/cypress/src/support/index.ts
Fixed code coverage setup
N/A
N/A
N/A
> RD-5228 Fix code coverage setup

- package-lock.json
Changes are consisting of executing `npm audit fix` in order to update `loaders-utils` locked package version.
N/A
N/A
N/A
> RD-6280 Resolved loader-utils vulnerability

- package-lock.json
RD-6398 fixing audit 
n/a
n/a
n/a
> RD-6398 fix audit for loader-utils

- package-lock.json
- packages/backend/package.json
RD-5881 there is no corresponding version of types/node 16.16.0 the only available version is 16.11.* or 16.18.*, so we decided to go for 16.11.68
n/a
n/a
n/a
> RD-5881 update types/nodes to v16.11.68

- package-lock.json
- packages/backend/package.json
- packages/backend/src/index.ts
- packages/backend/src/types.ts
- packages/backend/src/yaml.ts
- packages/backend/test/fixtures/blueprint.yaml
- packages/backend/test/yaml.test.ts
Added blueprint model types and serialization logic extracted from composer. To be reused in stage for blueprint generation.
N/A
Added extracted unit test.
N/A
> RD-6920 Add blueprint model types and serialization logic

- package-lock.json
- packages/backend/package.json
RD-7055 Details: https://github.com/cloudify-cosmo/cloudify-stage/pull/2444
N/A
N/A
> RD-7055 bump sequelize to 6.28.1 version to fix Snyk vulnerability

- package-lock.json
- packages/backend/package.json
Audit fix
N/A
CI verification only
N/A
> RD-7058 Audit fix

- packages/backend/src/blueprint.ts
- packages/backend/src/blueprints.ts
- packages/backend/src/index.ts
- packages/backend/test/blueprint.test.ts
Added blueprint builder utilities
N/A
Added unit test
Added jsdocs
> RND-96 Add blueprint builder utilities

- package-lock.json
- packages/backend/package.json
- packages/backend/src/git.ts
- packages/backend/src/index.ts
- packages/backend/test/git.test.ts
Added common git repositories inspection logic
N/A
Added unit test 
N/A
> RND-102 Add common git repositories inspection logic

- packages/backend/src/git.ts
- packages/backend/test/git.test.ts
It turns out the clone optimization feature that I originally used is not available in older git versions. Because of that TF wrapper system tests were failing. The new approach works with older git clients but it also performs even better.
N/A
Updated unit test
N/A
> RND-102 Use clone options compatible with older git versions and performing even better

- package-lock.json
- packages/cypress/package.json
- packages/frontend/package.json
- Updated semver version in `backend`
- Removed audit checks for `cypress` - this package by itself is a dev dependency. Since we are not auditing those I think it makes sense to disable audit for the whole package. As a side effect semver vulnerability is no longer an issue (ATM it is not fixable otherwise)
- Removed audit checks for `frontend` - this package has no prod dependencies, at the same time the `--production`/`--omit` functionality is buggy for workspaces (there are multiple issues filled in npm's github repo). Effectively, `npm run audit` was only checking dev dependencies defined in top-level package.json, and nothing else. Since our policy is not to audit dev dependencies I disabled the audit for the whole package. As a side effect semver vulnerability is no longer an issue …
> RND-919 Update semver version, remove audit checks for non-production dependencies

- package-lock.json
- packages/cypress/package.json
Changes consists of:
- updating `@cypress/code-coverage` package to the newest version
- executing `npm audit fix` command, to keep them in the most robust state 💪 
N/A
N/A
N/A
> RND-992 Resolved semver vulnerability

- packages/frontend/src/types.ts
- packages/frontend/test/types.test.ts
Jira ticket: https://cloudifysource.atlassian.net/browse/RND-538
```
leon@Leons-MacBook-Pro frontend % npm run test
> cloudify-ui-common-frontend@2.0.0 test
> npm run test:coverage
> cloudify-ui-common-frontend@2.0.0 test:coverage
> jest test --coverage
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
PASS  test/consts.test.ts
PASS …
```
> RND-538 Fix `getTypedValue` function

- package-lock.json
Fixing audit issues for workspace modules with npm audit fix:
backend
-------
axios - direct, 
ip - transitive,
mongodb - transitive
configs
------
braces - transitive,
micromatch - transitive
cypress
------
@babel/traverse - transitive
webpack - transitive
frontend
------
rollup - direct dev
N/A
N/A
N/A
> audit fix for workspaces
